# Trading Research System Configuration
# This file contains all configuration settings for the trading system

# Data Layer Configuration
data:
  bar_size: "1 hour"  # Options: '1 secs', '5 secs', '10 secs', '30 secs', '1 min', '5 mins', '15 mins', '30 mins', '1 hour', '1 day'
  signal_frequency: "1 hour"  # How often to generate signals (should match bar_size for most cases)
  trading_hours:
    start: "09:30"  # Market open
    end: "16:00"    # Market close
    timezone: "US/Eastern"
  valid_bar_sizes:
    - "1 secs"
    - "5 secs"
    - "10 secs"
    - "30 secs"
    - "1 min"
    - "5 mins"
    - "15 mins"
    - "30 mins"
    - "1 hour"
    - "1 day"

# Strategy Layer Configuration
strategy:
  etf_arbitrage:
    symbols: ["SPY", "RSP"]
    window: 180
    entry_threshold: 2
    exit_threshold: 0.1
    use_dynamic_thresholds: false
    confidence_level: 0.95
    distribution_type: "t"  # Options: 't', 'normal', 'skewnorm'
    use_rolling_hedge: true  # Use rolling hedge ratio instead of static
    hedge_window: 90  # Window for rolling hedge ratio calculation
    slippage: 0.01
    fee: 0.005
    shares_per_leg: 200
    initial_capital: 10000
    filter_trading_hours: true
    auto_detect_hours: false
    volatility_threshold: 0.001

# Execution Layer Configuration
execution:
  ib_connection:
    host: "127.0.0.1"
    live_port: 4001
    paper_port: 4002
    client_id: 13  # Dashboard/querying instance
    timeout: 20
  ib_trading_connection:
    host: "127.0.0.1"
    live_port: 4001
    paper_port: 4002
    client_id: 11  # Trading instance
    timeout: 20
  risk_limits:
    max_position_size_pct: 1.0  # 100% of portfolio
    max_daily_loss_pct: 0.05    # 5% daily loss limit
    max_drawdown_pct: 0.10      # 10% max drawdown
    max_trades_per_day: 500
    emergency_stop_loss_pct: 0.05  # 5% emergency stop
  backtest:
    default_duration: "6 M"  # 6 months for proper backtesting
    default_end_datetime: null  # Will use current time if null

# Analysis Layer Configuration
analysis:
  rolling_window: 60
  annualization_factor: 252  # Trading days per year
  var_confidence: 0.95
  plot_figsize: [15, 6]

# Infrastructure Configuration
infrastructure:
  notifications:
    telegram_enabled: true
    trade_updates: true
    pnl_updates: true
    system_alerts: true
  logging:
    level: "INFO"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Environment Configuration
environment:
  mode: "paper"  # Options: 'paper', 'live'
  debug: false
  verbose: true
